--Luis Jimenez
--MIS 422 A
--ASSIGNMENT 10

--TAL DISTRIBUTORS
--1
SELECT ORDER_NUM, ORDER_DATE, ORDERS.CUSTOMER_NUM, CUSTOMER_NAME
FROM ORDERS, CUSTOMER
WHERE ORDERS.CUSTOMER_NUM = CUSTOMER.CUSTOMER_NUM;

--4
SELECT CUSTOMER.CUSTOMER_NUM, CUSTOMER_NAME
FROM CUSTOMER, ORDERS
WHERE CUSTOMER.CUSTOMER_NUM = ORDERS.CUSTOMER_NUM
AND ORDER_DATE IN ('15-OCT-2015');

--19
SELECT ITEM.ITEM_NUM, DESCRIPTION, ON_HAND, ORDER_NUM, NUM_ORDERED
FROM ITEM
FULL OUTER JOIN ORDER_LINE ON ORDER_LINE.ITEM_NUM = ITEM.ITEM_NUM 
ORDER BY ITEM.ITEM_NUM;

--COLONIAL ADVENTURE TOURS
--10
SELECT F.TRIP_ID, F.TRIP_NAME, S.TRIP_ID, S.TRIP_NAME, F.START_LOCATION
FROM TRIP F, TRIP S
WHERE F.START_LOCATION = S.START_LOCATION 
AND F.TRIP_ID < S.TRIP_ID;

--13
SELECT CUSTOMER1.CUSTOMER1_NUM, LAST_NAME, FIRST_NAME
FROM CUSTOMER1, RESERVATION
WHERE STATE = 'NJ' AND CUSTOMER1.CUSTOMER1_NUM = RESERVATION.CUSTOMER1_NUM;

--SOLMARIS CONDOMINIUM GROUP
--7
SELECT SQR_FT, OWNER.OWNER_NUM, LAST_NAME, FIRST_NAME
FROM CONDO_UNIT, OWNER
WHERE OWNER.OWNER_NUM = CONDO_UNIT.OWNER_NUM AND LOCATION_NUM IN '1';

--14
SELECT CONDO_UNIT.CONDO_ID, SQR_FT, OWNER.OWNER_NUM, SERVICE_ID, EST_HOURS, SPENT_HOURS, CATEGORY_NUM
FROM CONDO_UNIT, OWNER, SERVICE_REQUEST
WHERE OWNER.OWNER_NUM = CONDO_UNIT.OWNER_NUM 
AND CONDO_UNIT.CONDO_ID = SERVICE_REQUEST.CONDO_ID
AND CATEGORY_NUM IN ('4');